#!/bin/bash

ec=ec.service


systemctl is-active $ec
context=$?
if [ $context -eq 0 ]
then
echo "$ec is started, stop it now"
systemctl stop $ec
fi


mosquitto_pub -t '/voicen/hey_wifi' -m '1'
python3 /usr/local/bin/hey_wifi.py
mosquitto_pub -t '/voicen/hey_wifi' -m '0'


if [ $context -eq 0 ]
then
echo "recover $ec"
systemctl start $ec
fi


